In [2]:
#a 

import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'City': ['New York', 'London', 'Paris']}

df = pd.DataFrame(data)
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris


In [4]:
import pandas as pd

data = [['Alice', 25, 'New York'],
        ['Bob', 30, 'London'],
        ['Charlie', 22, 'Paris']]

df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris


In [6]:
import pandas as pd

data = [{'Name': 'Alice', 'Age': 25, 'City': 'New York'},
        {'Name': 'Bob', 'Age': 30, 'City': 'London'},
        {'Name': 'Charlie', 'Age': 22, 'City': 'Paris'}]

df = pd.DataFrame(data)
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris


In [ ]:
import pandas as pd

# From CSV
df_csv = pd.read_csv('data.csv')
print(df_csv.head())

# From Excel
df_excel = pd.read_excel('data.xlsx')
print(df_excel.head())


In [8]:
import pandas as pd
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_np = pd.DataFrame(data, columns=['ColA', 'ColB', 'ColC'])
print(df_np)


   ColA  ColB  ColC
0     1     2     3
1     4     5     6
2     7     8     9


In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/your_folder/your_file.csv')
print(df.head())


In [12]:
from sklearn.datasets import load_iris, load_digits, load_diabetes

# Iris Dataset
iris = load_iris()
X_iris, y_iris = iris.data, iris.target
print("Iris Data:\n", X_iris[:5])

# Digits Dataset
digits = load_digits()
X_digits, y_digits = digits.data, digits.target
print("\nDigits Data:\n", X_digits[:5])

# Diabetes Dataset
diabetes = load_diabetes()
X_diabetes, y_diabetes = diabetes.data, diabetes.target
print("\nDiabetes Data:\n", X_diabetes[:5])


Iris Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Digits Data:
 [[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
  15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
   0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
   0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
   3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
  16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
   0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
 [ 0.  0.  0.  4. 15. 12.  0.  0.  0.  0.  3. 16. 15. 14.  0.  0.  0.  0.
   8. 13.  8. 16.  0.  0.  0.  0.  1.  6. 15. 11.  0.  0.  0.  1.  8. 13.
  15.  1.  0.  0.  0.  9. 16. 16.  5.  0.  0.  0.  0.  3. 13. 16. 16. 11.
   5.  0.  0.  0.  0.  3. 11. 16.  9.  0.]
 [ 0.  0.  7. 15. 13.  1.  0.  0.  0.  8. 13.  6. 15.  4.  0.  0.  0.  2.
   1. 13

In [ ]:
from google.colab import files

uploaded = files.upload()


In [14]:
#b) Write a python program to compute Mean, Median, Mode, Variance, Standard Deviation using Datasets

import pandas as pd
from scipy import stats

# Sample dataset
data = {'Marks': [80, 85, 90, 75, 95, 85, 80]}
df = pd.DataFrame(data)

mean = df['Marks'].mean()
median = df['Marks'].median()
mode = df['Marks'].mode()[0]
variance = df['Marks'].var()
std_dev = df['Marks'].std()

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Mean: 84.28571428571429
Median: 85.0
Mode: 80
Variance: 45.23809523809524
Standard Deviation: 6.7259270913454925


In [16]:
#c)Demonstrate various data pre-processing techniques for a given dataset. Write a python program to compute
#i. Reshaping the data
#ii.Filtering the data
#iii.Merging the data
#iv.Handling the missing values in datasets
#v.Feature Normalization: Min-max normalization, Scalar Normalization etc.

import pandas as pd
import numpy as np

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', np.nan],
        'Age': [25, 30, np.nan, 35, 40],
        'Salary': [50000, 60000, 55000, np.nan, 65000],
        'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo']}

df = pd.DataFrame(data)
print("Original Data:\n", df)


Original Data:
       Name   Age   Salary      City
0    Alice  25.0  50000.0  New York
1      Bob  30.0  60000.0    London
2  Charlie   NaN  55000.0     Paris
3    David  35.0      NaN    Berlin
4      NaN  40.0  65000.0     Tokyo


In [30]:
# Using pivot_table for reshaping
reshaped = df.pivot_table(values='Salary', index='City')
print("\nReshaped Data:\n", reshaped)



Reshaped Data:
             Salary
City              
Berlin    0.507093
London    1.183216
New York -1.521278
Paris    -0.169031


In [20]:
# Filter rows where Age > 30
filtered = df[df['Age'] > 30]
print("\nFiltered Data (Age > 30):\n", filtered)



Filtered Data (Age > 30):
     Name   Age   Salary    City
3  David  35.0      NaN  Berlin
4    NaN  40.0  65000.0   Tokyo


In [22]:
data1 = {'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']}
data2 = {'ID': [1, 2, 3], 'Salary': [50000, 60000, 55000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

merged = pd.merge(df1, df2, on='ID')
print("\nMerged Data:\n", merged)



Merged Data:
    ID     Name  Salary
0   1    Alice   50000
1   2      Bob   60000
2   3  Charlie   55000


In [24]:
# Fill missing values with mean
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

# Drop rows with missing names
df.dropna(subset=['Name'], inplace=True)

print("\nAfter Handling Missing Values:\n", df)



After Handling Missing Values:
       Name   Age   Salary      City
0    Alice  25.0  50000.0  New York
1      Bob  30.0  60000.0    London
2  Charlie  32.5  55000.0     Paris
3    David  35.0  57500.0    Berlin


C:\Users\Omkar\AppData\Local\Temp\ipykernel_21496\2558915244.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
C:\Users\Omkar\AppData\Local\Temp\ipykernel_21496\2558915244.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exa

In [26]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])

print("\nAfter Min-Max Normalization:\n", df)



After Min-Max Normalization:
       Name   Age  Salary      City
0    Alice  0.00    0.00  New York
1      Bob  0.50    1.00    London
2  Charlie  0.75    0.50     Paris
3    David  1.00    0.75    Berlin


In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])

print("\nAfter Z-score Normalization:\n", df)



After Z-score Normalization:
       Name       Age    Salary      City
0    Alice -1.521278 -1.521278  New York
1      Bob -0.169031  1.183216    London
2  Charlie  0.507093 -0.169031     Paris
3    David  1.183216  0.507093    Berlin
