In [1]:
#a)Design and implement a neural network that acts as a AND classifier for binary input

import numpy as np

def step(x):
    return 1 if x >= 0 else 0

def AND(x1, x2):
    w1, w2, b = 1, 1, -1.5
    return step(w1*x1 + w2*x2 + b)

# Test
for x1 in [0,1]:
    for x2 in [0,1]:
        print(f"Input: ({x1},{x2}) → Output: {AND(x1,x2)}")


Input: (0,0) → Output: 0
Input: (0,1) → Output: 0
Input: (1,0) → Output: 0
Input: (1,1) → Output: 1


In [4]:
#b) Design and implement a neural network that acts as a OR classifier for binary input

def OR(x1, x2):
    w1, w2, b = 1, 1, -0.5
    return step(w1*x1 + w2*x2 + b)

for x1 in [0,1]:
    for x2 in [0,1]:
        print(f"Input: ({x1},{x2}) → Output: {OR(x1,x2)}")


Input: (0,0) → Output: 0
Input: (0,1) → Output: 1
Input: (1,0) → Output: 1
Input: (1,1) → Output: 1


In [ ]:
#c) Design and implement a neural network that acts as a NAND classifier for binary input
#d) Design and implement a neural network that acts as a XOR classifier for binary input, Comment on the inability of this NN to classify the i/p data

def NAND(x1, x2):
    w1, w2, b = -1, -1, 1.5
    return step(w1*x1 + w2*x2 + b)

for x1 in [0,1]:
    for x2 in [0,1]:
        print(f"Input: ({x1},{x2}) → Output: {NAND(x1,x2)}")


def XOR(x1, x2):
    # Hidden layer outputs
    n1 = NAND(x1, x2)
    n2 = OR(x1, x2)
    # Final output using AND gate
    return AND(n1, n2)

for x1 in [0,1]:
    for x2 in [0,1]:
        print(f"Input: ({x1},{x2}) → Output: {XOR(x1,x2)}")


In [ ]:
!pip install tensorflow

In [1]:
#e)Design and implement a sequential, dense neural network that acts as a classifier for the Iris dataset, tune your neural network with different hyperparameter values for learning rate, architecture and epochs

# --------------------------------------------
# Neural Network Classifier for Iris Dataset
# --------------------------------------------

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelBinarizer

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# One-hot encode output (3 classes)
encoder = LabelBinarizer()
y = encoder.fit_transform(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Sequential model
model = Sequential([
    Dense(12, input_dim=4, activation='relu'),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')  # 3 output classes
])

# Compile model (you can change learning_rate for tuning)
model.compile(optimizer=Adam(learning_rate=0.01),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train model (you can change epochs for tuning)
model.fit(X_train, y_train, epochs=50, batch_size=8, verbose=1)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Accuracy:", round(accuracy*100, 2), "%")


C:\Users\Omkar\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.5000 - loss: 1.0503
Epoch 2/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8167 - loss: 0.6472 
Epoch 3/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8083 - loss: 0.4130 
Epoch 4/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3218 
Epoch 5/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2653 
Epoch 6/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9250 - loss: 0.2155 
Epoch 7/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9250 - loss: 0.1608 
Epoch 8/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9583 - loss: 0.1188 
Epoch 9/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9583 - loss: 0.0987 
Epoch 10/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9667 - loss: 0.0880 
Epoch 11/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9500 - loss: 0.0950 
Epoch 12/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0

In [10]:
#f) Design and implement a sequential, dense neural network that acts as a classifier for the diabetes dataset provided to you in class, tune your neural network with different hyperparameter values for learning rate, architecture and epochs.

# --------------------------------------------
# Neural Network Classifier for Diabetes Dataset
# --------------------------------------------

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Load dataset
data = load_diabetes()
X = data.data
y = data.target

# Convert target to binary (for classification)
# We'll classify as 1 if diabetes measure > mean, else 0
y = np.where(y > np.mean(y), 1, 0)

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Sequential model
model = Sequential([
    Dense(12, input_dim=X_train.shape[1], activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')  # Binary classification
])

# Compile model (change learning rate to tune)
model.compile(optimizer=Adam(learning_rate=0.01),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train model (change epochs to tune)
model.fit(X_train, y_train, epochs=50, batch_size=8, verbose=1)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Accuracy:", round(accuracy*100, 2), "%")


ModuleNotFoundError: No module named 'tensorflow'

In [4]:
#g) Design and implement a sequential, dense neural network that acts as a classifier for the heart dataset provided in class, tune your neural network with different hyperparameter values for learning rate, architecture and epochs.

# --------------------------------------------
# Neural Network Classifier for Heart Dataset
# --------------------------------------------

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset (replace 'heart.csv' with your actual file)
data = pd.read_csv("heart.csv")

# Split features (X) and target (y)
X = data.drop('target', axis=1)
y = data['target']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build Sequential model
model = Sequential([
    Dense(12, input_dim=X_train.shape[1], activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile with different learning rate
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train with different epochs
model.fit(X_train, y_train, epochs=100, batch_size=8, verbose=1)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Accuracy:", round(accuracy*100, 2), "%")


ModuleNotFoundError: No module named 'tensorflow'

In [9]:
pip install tensorflow


^C
Note: you may need to restart the kernel to use updated packages.
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/f9/37/b97abb360b551fbf5870a0ee07e39ff9c655e6e3e2f839bc88be81361842/tensorflow-2.20.0-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/8f/aa/ba0014cc4659328dc818a28827be78e6d97312ab0cb98105a770924dc11e/absl_py-2.3.1-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=24.3.25 from https://files.pythonhosted.org/packages/ee/1b/00a78aa2e8fbd63f9af08c9c19e6deb3d5d66b4dda677a0f61654680ee89/flatbuffers-25.9.23-py2.py3-none-any.whl.metadata
  Obtaining dependency information for gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: C:\Users\malij\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [8]:
import tensorflow as tf
print(tf.__version__)


ModuleNotFoundError: No module named 'tensorflow'

In [1]:
#for AND gate


import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [0],
              [0],
              [1]])

np.random.seed(42)

weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.1

for epoch in range(10000):
    z = np.dot(X, weights) + bias
    output = sigmoid(z)
    error = y - output
    d_output = error * sigmoid_derivative(output)
    weights += np.dot(X.T, d_output) * lr
    bias += np.sum(d_output) * lr

print("Trained weights:\n", weights)
print("Trained bias:\n", bias)

for x_input in X:
    z = np.dot(x_input, weights) + bias
    pred = sigmoid(z)
    print(f"Input: {x_input}, Output: {np.round(pred)}")


Trained weights:
 [[5.47798131]
 [5.47798133]]
Trained bias:
 [-8.30967052]
Input: [0 0], Output: [0.]
Input: [0 1], Output: [0.]
Input: [1 0], Output: [0.]
Input: [1 1], Output: [1.]


In [2]:

#for OR gate

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [1]])

np.random.seed(42)

weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.1

for epoch in range(10000):
    z = np.dot(X, weights) + bias
    output = sigmoid(z)
    error = y - output
    d_output = error * sigmoid_derivative(output)
    weights += np.dot(X.T, d_output) * lr
    bias += np.sum(d_output) * lr

print("Trained weights:\n", weights)
print("Trained bias:\n", bias)

for x_input in X:
    z = np.dot(x_input, weights) + bias
    pred = sigmoid(z)
    print(f"Input: {x_input}, Output: {np.round(pred)}")


Trained weights:
 [[6.18070516]
 [6.18080141]]
Trained bias:
 [-2.84421937]
Input: [0 0], Output: [0.]
Input: [0 1], Output: [1.]
Input: [1 0], Output: [1.]
Input: [1 1], Output: [1.]


In [3]:
#for NAND gate

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[1],
              [1],
              [1],
              [0]])

np.random.seed(42)

weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.1

for epoch in range(10000):
    z = np.dot(X, weights) + bias
    output = sigmoid(z)
    error = y - output
    d_output = error * sigmoid_derivative(output)
    weights += np.dot(X.T, d_output) * lr
    bias += np.sum(d_output) * lr

print("Trained weights:\n", weights)
print("Trained bias:\n", bias)

for x_input in X:
    z = np.dot(x_input, weights) + bias
    pred = sigmoid(z)
    print(f"Input: {x_input}, Output: {np.round(pred)}")


Trained weights:
 [[-5.47036166]
 [-5.47036166]]
Trained bias:
 [8.29827497]
Input: [0 0], Output: [1.]
Input: [0 1], Output: [1.]
Input: [1 0], Output: [1.]
Input: [1 1], Output: [0.]


In [4]:
#for XOR gate

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(42)

weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.1

for epoch in range(10000):
    z = np.dot(X, weights) + bias
    output = sigmoid(z)
    error = y - output
    d_output = error * sigmoid_derivative(output)
    weights += np.dot(X.T, d_output) * lr
    bias += np.sum(d_output) * lr

print("Trained weights:\n", weights)
print("Trained bias:\n", bias)

for x_input in X:
    z = np.dot(x_input, weights) + bias
    pred = sigmoid(z)
    print(f"Input: {x_input}, Output: {np.round(pred)}")


Trained weights:
 [[2.47335969e-16]
 [2.47930698e-16]]
Trained bias:
 [-3.31215607e-16]
Input: [0 0], Output: [0.]
Input: [0 1], Output: [0.]
Input: [1 0], Output: [0.]
Input: [1 1], Output: [0.]
